// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbgnicypaeuadafogyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ25pY3lwYWV1YWRhZm9neXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MTU5ODQsImV4cCI6MjA1MTI5MTk4NH0.PbDlOlwcQQotPK5SCSl9h43QTbdUJ7fP7qf2e4Xk4yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);